version: "3.8"


services:
  deb-repo:
    container_name: deb-repo
    build: .
    ports:
      - "10001:80"
    volumes:
      - ${PWD}/data:/data 
    networks:
      deb-agi:
        ipv4_address: 172.16.16.2

  istemci:
    tty: true
    container_name: deb-istemci
    image: ubuntu:focal
#    command: echo "deb http://172.16.16.2 trusty main" > /etc/apt/sources.list
    networks:
      deb-agi:
        ipv4_address: 172.16.16.3

networks:
  deb-agi:
    driver: bridge
    ipam:
      config:
      - subnet: "172.16.16.0/24"
        gateway: 172.16.16.1
